### PR TITLE
Minor code tweaks / get rid of Standard warnings

### PR DESCRIPTION
**Pull request by dmitrizagidulin**

### CODE REVIEW

**Comment by christiansmith** [comment]
A couple things before merging. We need to establish some organizational and formatting conventions for this new stuff that hasn't been discussed much.

First, I've been placing the static schema getter up toward the top of the class definition. Open to placing it at the bottom too, but we should be consistent. What are the pros and cons? Are there any conventions for sorting methods by static/prototype, alphabetical, lexicographic, etc?

I think putting it up top makes it clear that the schema is defined for the class right away, which is important if the class is extending JSONDocument. However, other than knowing that it's there, it's not an important detail that will be revisited continuously. Which makes a good argument for putting such methods at the bottom of the class declaration. What are your thoughts?

Also, is there a convention around whitespace in destructuring assignment expressions? I have seen a ton of variations and not sure what's going to be the right thing to use with respect to Standard JavaScript formatting and so on. We should go with a standard common thing if there is one.

Good catches on everything else. Thanks!

**Comment by dmitrizagidulin** [comment]
> Also, is there a convention around whitespace in destructuring assignment expressions?

The convention is: there is _always_ a space after a comma. In destructuring assignments, and everywhere else. Otherwise, the terrorists win.

**Comment by dmitrizagidulin** [comment]
> Are there any conventions for sorting methods by static/prototype, alphabetical, lexicographic, etc?

Sadly, not that I could find :( Which means that the issue degenerates into personal preferences. For example, some people always put static methods on top, some on the bottom. Some people do alphabetical ordering of functions, but others try to minimize "vertical distance" - that is try and group related functions together, sort of. For example, in "Clean Code", Robert C. Martin advocates that functions should read "like the headlines of a newspaper", telling a story.

I personally disagree with Martin, though. On the one hand, I'm all for making code more readable to humans, above anything else. However, there's two main benefits to ordering functions alphabetically. One, it's an easy and _consistent_ scheme - there is no need for each developer to try and subjectively guess what is the most intuitive ordering. Easy to enforce. And two, for people who are using code editors without a method outline view, or ones that don't allow Eclipse-style "ctrl-click" to jump to a function definition, ordering by alphabetical allows for easy mental navigation when scrolling around in a text file. (Meaning, we all know how to navigate something laid out like a dictionary or encyclopedia).

So, upshot of all of that: I propose we do static methods first, and instance methods second. And within each category, order alphabetically.

**Comment by dmitrizagidulin** [comment]
I suppose there is also the question of - where do getters/setters go, in all of that? Sorted alphabetically among other methods, or in a separate category? From what I can tell, there is most agreement about grouping class _member_ variables at the very top, before even the constructor. And since Javascript doesn't really have explicit member variable declaration (outside of constructors or other functions), getters and setters might be the closest thing to that. But does it make sense to put getters/setters before the constructor? No idea.

**Comment by christiansmith** [comment]
@dmitrizagidulin good thoughts. Assuming Standard JavaScript formatters/linters agree, let's go with the space after comma rule. That would have been my first thought, but I keep seeing people doing destructuring without commas and have tried to go with the flow there. In retrospect, this reminds me of...

``` javascript
var a = 0
  , b = 1
  , c = 2
  ;
```

... which has a sort of eccentric "which I were a lisper" quality while only being marginally (and arguably) less error-prone to edit than...

``` javascript
var a = 0,
    b = 1,
    c = 2;
```

... where everything is simplified by...

``` javascript
var a = 1
var b = 2
var c = 3
```

I'm good with ordering by static vs proto (static on top) and otherwise alphabetically. Have gone more with the "reads like a story" very often in the past, but from experience that is quite arbitrary as everyone approaches reading new code differently. Alphabetical is better for finding what one is looking for. It's strikes me that comments are better able to tell the story because much code is impossibly non-linear in definition. Perhaps the comment above a class or at the top of the module is the right place to explain composition and context. 

Also, I wonder if a strong urge to group related functions together would be better satisfied by other kinds of organization, such as breaking out related behaviors into a different class or module.

The only other question about conventions is what to do with the constructor. Should it be inline with alphabetical methods or, in contrast "pinned" to the top of the class? I'd go with top of the class if that's agreeable.

**Comment by christiansmith** [comment]
Ok... the only other question for now... :p

**Comment by dmitrizagidulin** [comment]
Yeah, I have a strong preference for pinning the constructor up top as well. 

So what do you think about getters/setters? Alphabetical with the other methods?

**Comment by christiansmith** [comment]
Damn, why can't anything be easy. Need to ponder this.

**Comment by dmitrizagidulin** [comment]
K, reordered per our conversations. (Static methods on top).

**Comment by christiansmith** [comment]
Thanks!

**Comment by christiansmith** [comment]
oh, also let's remember to use conventional changelog style git messages :)

**Pull request merged**
